### PR TITLE
Feature/kris

### PR DESCRIPTION
**Pull request by thekjp**
Please review my code.

### CODE REVIEW

**Review by gracelau — COMMENTED** [review]
great job, completed all tasks

**Review by Green-Eggs-And-SAM — APPROVED** [review]
10/10 sam approves

**Review by gracelau — APPROVED** [review]

**Review by hemidemisemisara — APPROVED** [review]
nice!

**Review by Green-Eggs-And-SAM — APPROVED** [review]
excelsent

**Review by gracelau — APPROVED** [review]
changes look good

**Pull request merged**
